//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCA.Reports {
    
    
    public partial class Reports {
        
        /// <summary>
        /// ucStudentReports control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OCA.UserControls.UCStudentReports ucStudentReports;
        
        /// <summary>
        /// ucStaffReports control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OCA.UserControls.UCStaffReports ucStaffReports;
        
        /// <summary>
        /// ucOtherReports control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OCA.UserControls.UCOtherReports ucOtherReports;
    }
}
