//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCA.Student {
    
    
    public partial class StudentCourses {
        
        /// <summary>
        /// uppnlStudentCourseView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel uppnlStudentCourseView;
        
        /// <summary>
        /// ucStudentCourseView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OCA.UserControls.UCStudentCoursesView ucStudentCourseView;
        
        /// <summary>
        /// uppnlStudentCourseAddEdit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel uppnlStudentCourseAddEdit;
        
        /// <summary>
        /// ucStudentCourseAddEdit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OCA.UserControls.UCStudentCoursesAddEdit ucStudentCourseAddEdit;
    }
}
